### ISSUE TITLE
What's the proper way to link to libEGL dynamically?

### ISSUE THREAD

**Issue by kvark** [timothee-haudebourg/khronos-egl#13]
The readme says:
> You can access the EGL API using an Instance object defined by either statically linking with libEGL.so at compile time, or dynamically loading the EGL library at runtime.

However, it looks like some systems have `libEGL.so.1` but no `libEGL.so`. See https://github.com/gfx-rs/wgpu-rs/issues/751#issuecomment-774790048

**Comment by timothee-haudebourg** [comment]
Yes that was to be expected if you are using the `DynamicInstance::load` or `DynamicInstance::load_required` functions since they will try to load the "libEGL.so" file. You can use  `DynamicInstance::load_from_filename` or `DynamicInstance::load_required_from_filename` to try another name, or even better do it in two steps (as showed in the readme) to try multiple filenames.

**Comment by kvark** [comment]
I don't mind using `load_from_name`, but what I'm asking if there is a way to load this without guesswork. If targeting Linux only, shouldn't it always be named `libEGL.so.1`? the `libEGL.so` would just be a symlink to this.

**Comment by timothee-haudebourg** [comment]
Right, I'm not familiar with these kind of naming conventions but this seems consistent across many distributions as far as I searched. It seems that the presence of `libEGL.so` implies `libEGL.so.1` but not the other way around so I should indeed search for the latter instead. If correct, this should not affect backward compatibility.

**Comment by timothee-haudebourg** [comment]
As of version `3.0.1`, `libEGL.so.1` is loaded by default instead of `libEGL.so`, which should work on more systems.
