### ISSUE TITLE
Use RTLD_NODELETE for loading the library

### ISSUE THREAD

**Issue by kvark** [timothee-haudebourg/khronos-egl#14]
See discussion around https://github.com/gfx-rs/wgpu/issues/246#issuecomment-783542762

**Comment by timothee-haudebourg** [comment]
That's unfortunate. I'll add the flag then.

The relevant issue is https://github.com/nagisa/rust_libloading/issues/41

**Comment by kvark** [comment]
Could you clarify why this is unfortunate? Sorry, I didn't dig into all the context here.

**Comment by Aaron1011** [comment]
@kvark: The root cause of https://github.com/nagisa/rust_libloading/issues/41 is [this glibc bug](https://sourceware.org/bugzilla/show_bug.cgi?id=21032). Ideally, you would be able to `dlclose` a shared library when you're done using it, and glibc would take care of removing any TLS destructors from that library.
