### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by kvark** [timothee-haudebourg/khronos-egl#6]
Hitting an assert when building: https://github.com/gfx-rs/gfx/pull/3470/checks?check_run_id=1372587404#step:5:83
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CrossCompilation', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/khronos-egl-2.1.1/build.rs:7:10

**Comment by timothee-haudebourg** [comment]
This comes from the `pkg_config` crate that is used in `build.rs` to find the EGL lib. It seems not happy with your cross compilation environment.

According to [the doc](https://docs.rs/pkg-config/0.3.19/pkg_config/), you need to set the `PKG_CONFIG_ALLOW_CROSS` environment variable to ignore this error:
> The pkg-config command usually doesn't support cross-compilation, and this crate prevents it from selecting incompatible versions of libraries. Setting PKG_CONFIG_ALLOW_CROSS=1 disables this protection, which is likely to cause linking errors, unless pkg-config has been configured to use appropriate sysroot and search paths for the target platform.

If I understand well, since version `0.3.19` it is enabled by default if either `PKG_CONFIG` or `PKG_CONFIG_SYSROOT_DIR` are set (see [#86](https://github.com/rust-lang/pkg-config-rs/pull/86)).

**Comment by kvark** [comment]
Thank you for the info! Trying this out in https://github.com/gfx-rs/gfx/pull/3480
